server:
  shutdown: "immediate"
  error:
    include-binding-errors: "always"
    include-exception: "true"
    include-message: "always"
    include-stacktrace: "always"

spring:
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        format_sql: "true"
  devtools:
    livereload:
      enabled: "true"
  output:
    ansi:
      enabled: always

logging:
  level:
    com:
      github:
        overz: debug
