debug: "${DEBUG:false}"

server:
  port: "${APP_PORT:3000}"
  address: "${APP_ADDRESS:0.0.0.0}"
  shutdown: "graceful"
  servlet:
    context-path: "${APP_CONTEXT_PATH:}"
    session:
      cookie:
        http-only: "true"
        secure: "true"
  error:
    include-binding-errors: "never"
    include-message: "never"
    include-path: "always"
    include-stacktrace: "never"
    include-exception: "false"

spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
  application:
    name: "@project.artifactId@"
  output:
    ansi:
      enabled: never
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  threads:
    virtual:
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: "${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}"
    username: "${DATABASE_USERNAME:postgres}"
    password: "${DATABASE_PASSWORD:postgres}"
    driver-class-name: "${DATABASE_DRIVER:org.postgresql.Driver}"
    hikari:
      maximum-pool-size: "${HIKARI_MAXIMUM_POOL_SIZE:10}"
      minimum-idle: "${HIKARI_MINIMUM_IDLE:2}"
      auto-commit: "${HIKARI_AUTO_COMMIT:true}"
      max-lifetime: "${HIKARI_MAX_LIFETIME:3600000}"
  jpa:
    hibernate:
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
  kafka:
    bootstrap-servers: "${KAFKA_BROKERS:localhost:19092,localhost:29092}"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.ByteArraySerializer"
      value-serializer: "org.apache.kafka.common.serialization.ByteArraySerializer"

# https://camel.apache.org/components/4.10.x/cxf-component.html
cxf:
  path: "/services"

# https://camel.apache.org/camel-spring-boot/4.10.x/spring-boot.html
camel:
  servlet:
    mapping:
      context-path: "/*"
  rest:
    context-path: "/"
    component: "servlet"
    client-request-validation: true
    binding-mode: auto
    api-property:
      title: "@project.artifactId@"
      version: "@project.version@"
  dataformat:
    jackson:
      pretty-print: true
      auto-discover-object-mapper: true
  component:
    kafka:
      brokers: "${KAFKA_BROKERS:localhost:19092,localhost:29092}"
      client-id: "${spring.application.name}-${random.uuid}"
      request-required-acks: "all"
      retries: "3"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer"

management:
  server:
    port: "${APP_MANAGMENT_PORT:9090}"
  endpoints:
    access:
      default: read_only
    web:
      exposure:
        include:
          - health

resilience4j:
  retry:
    configs:
      default:
        max-attempts: "${R4J_MAX_ATTEMPTS:8}"
        wait-duration: "${R4J_WAIT_DURATION:2s}"
        fail-after-max-attempts: "${R4J_FAIL_AFTER_MAX_ATTEMPTS:true}"
        enable-exponential-backoff: "${R4J_ENABLE_EXPONENTIAL_BACKOFF:true}"
        exponential-backoff-multiplier: "${R4J_EXPONENTIAL_BACKOFF_MULTIPLIER:1.4}"
        exponential-max-wait-duration: "${R4J_EXPONENTIAL_MAX_WAIT_DURATION:3m}"
        retry-exceptions:
          - org.springframework.web.client.RestClientException
          - java.net.SocketTimeoutException

app:
  services:
    test-service: "${TEST_SERVICE_ENDPOINT:/TestService}"
  topics:
    order: "${TOPIC_ORDER:test}"
  files:
    input-test-files: "file:${TEST_FILES_DIR:@project.basedir@/test-files/input}"
    output-test-files: "file:${TEST_FILES_DIR:@project.basedir@/test-files/output}"
  api:
    timeout: "60S"
    notification:
      base-url: "${NOTIFICATION_SERVICE_BASE_URL:http://localhost:3001/v1}"